const {test}=require('node:test'),assert=require('node:assert/strict');
test('atomic booking, idempotency, price checks and private availability',async()=>{
 const {consultationPublic,validateTypes}=await import('../server/consultations.mjs'),{base,fields,unpack}=await import('../server/firestore-rest.mjs');
 let version=0,notifications=0;const docs=new Map(),put=(p,d)=>docs.set(p,{name:base+'/'+p,fields:fields(d),updateTime:'v'+(++version)}),slotId='00000000-0000-4000-8000-000000000001',types=[{id:'technical',name:'اختبار',nameEn:'Test',duration:30,priceBaisa:12500,active:true}];
 put('portfolioSettings/consultations',{typesJson:JSON.stringify(types)});put('portfolioConsultationSlots/'+slotId,{typeId:'technical',duration:30,start:new Date(Date.now()+86400000).toISOString(),end:new Date(Date.now()+88200000).toISOString(),open:true,bookingId:''});
 const db={read:async p=>structuredClone(docs.get(p)||null),api:async(path,b)=>{if(path.endsWith(':runQuery'))return [...docs.entries()].filter(([p])=>p.startsWith('portfolioConsultationSlots/')).map(([,document])=>({document:structuredClone(document)}));for(const w of b.writes){const p=(w.update?.name||w.verify).slice(base.length+1),old=docs.get(p),c=w.currentDocument;if(c?.exists===false&&old||c?.updateTime&&c.updateTime!==old?.updateTime)throw Object.assign(Error(),{code:'FAILED_PRECONDITION'});}for(const w of b.writes){if(w.verify)continue;const p=w.update.name.slice(base.length+1);put(p,{...(w.updateMask?unpack(docs.get(p)):{}),...unpack({fields:w.update.fields})});}return {};}};
 const env={SITE_URL:'https://test.invalid'},input=id=>({requestId:id,slotId,name:'Synthetic Person',phone:'+96899999999',email:'test@example.invalid',message:'test',consent:true,priceBaisa:12500,duration:30}),req=i=>new Request(env.SITE_URL+'/api/consultations',{method:'POST',headers:{Origin:env.SITE_URL,'CF-Connecting-IP':'127.0.0.1'},body:JSON.stringify(i)}),call=r=>consultationPublic(r,env,{db,notify:()=>notifications++});
 const a=input('00000000-0000-4000-8000-000000000002'),b=input('00000000-0000-4000-8000-000000000003');assert.throws(()=>validateTypes([{...types[0],priceBaisa:-1}]));assert.equal((await call(req({...a,priceBaisa:1}))).status,409);const results=await Promise.all([call(req(a)),call(req(b))]);assert.deepEqual(results.map(r=>r.status).sort(),[201,409]);assert.equal(notifications,1);const winner=results[0].status===201?a:b;assert.equal((await call(req(winner))).status,200);assert.equal(notifications,1);assert.equal((await(await call(new Request(env.SITE_URL+'/api/consultations'))).json()).slots.length,0);
 const {adminAPI}=await import('../server/admin-api.mjs');assert.equal((await adminAPI(new Request(env.SITE_URL+'/api/admin/consultations'),env,{auth:async()=>null,db})).status,401);
});
