const {test}=require('node:test'),assert=require('node:assert/strict');
test('monthly ledger scans all pages, distinguishes received date and ignores void expenses and unpaid invoices',async()=>{
 const {ledgerAPI,validateExpense}=await import('../server/ledger.mjs'),{fields,base}=await import('../server/firestore-rest.mjs');let receiptPages=0;
 const doc=(id,data)=>({document:{name:base+'/x/'+id,updateTime:'v1',fields:fields(data)}});
 const db={api:async(p,{structuredQuery:q})=>{assert.equal(q.limit,250);const filters=q.where.compositeFilter.filters;assert.equal(filters[0].fieldFilter.value.stringValue,'2026-09-01');assert.equal(filters[1].fieldFilter.value.stringValue,'2026-10-01');if(q.from[0].collectionId==='portfolioExpenses')return [doc('a',{date:'2026-09-02',amountBaisa:100,status:'active'}),doc('b',{date:'2026-09-03',amountBaisa:999,status:'void'})];if(q.orderBy[0].field.fieldPath==='paidDate'){receiptPages++;return q.startAt?[doc('last',{status:'paid',date:'2026-08-01',paidDate:'2026-09-09',totalBaisa:5})]:Array.from({length:250},(_,i)=>doc('i'+i,{status:'paid',paidDate:'2026-09-01',date:'2026-08-01',totalBaisa:10}));}return [doc('draft',{status:'draft',date:'2026-09-01',totalBaisa:999}),doc('old',{status:'paid',date:'2026-09-01',paidDate:'',totalBaisa:500})];}};
 const r=await ledgerAPI(new Request('https://a.test/api/admin/ledger?month=2026-09'),{},db,'ledger'),body=await r.json();assert.equal(receiptPages,2);assert.equal(body.incomeBaisa,2505);assert.equal(body.expenseBaisa,100);assert.equal(body.netBaisa,2405);assert.equal(body.invoiceBaisa,500);assert.equal(body.missingPaymentDate,1);assert.equal(body.receipts.length,251);
 assert.throws(()=>validateExpense({name:'x',notes:'',date:'2026-02-30',amountBaisa:1,status:'active'}));assert.throws(()=>validateExpense({name:'x',notes:'',date:'2026-09-01',amountBaisa:-1,status:'active'}));
 const {adminAPI}=await import('../server/admin-api.mjs');for(const route of ['ledger?month=2026-09','expenses/00000000-0000-4000-8000-000000000001','invoices/00000000-0000-4000-8000-000000000001/email'])assert.equal((await adminAPI(new Request('https://a.test/api/admin/'+route),{}, {auth:async()=>null,db})).status,401);
});
test('paid invoices require an actual received date and email header injection is rejected',async()=>{const {validateInvoice}=await import('../server/invoices.mjs'),data={name:'Customer',phone:'99999999',project:'Project',notes:'',date:'2026-09-09',requestId:'',status:'paid',logo:'',items:[{name:'Part',quantity:1,priceBaisa:125}],discountBaisa:0};assert.throws(()=>validateInvoice(data));assert.equal(validateInvoice({...data,paidDate:'2026-09-08'}).paidDate,'2026-09-08');assert.throws(()=>validateInvoice({...data,paidDate:'2026-09-08',email:'a@test.com\r\nBcc: other@test.com'}));});
test('PDF email creates a private MIME attachment, protects version/origin, prevents duplicate sends and quarantines ambiguous outcomes',async()=>{
 const {invoiceMail}=await import('../server/invoice-mail.mjs'),{fields,base,unpack}=await import('../server/firestore-rest.mjs');const id='00000000-0000-4000-8000-000000000001',path='portfolioInvoices/'+id;let v=1,sends=0,mode='success';const docs=new Map([[path,{name:base+'/'+path,updateTime:'v1',fields:fields({name:'Synthetic Customer',project:'Synthetic project',email:'test@example.invalid',reference:'SW-001',status:'issued'})}],['portfolioSettings/gmail',{fields:fields({credential:'mock'})}]]);
 const db={read:async p=>docs.get(p),patch:async(p,data)=>{docs.set(p,{...docs.get(p),fields:{...docs.get(p).fields,...fields(data)},updateTime:'v'+(++v)});},api:async(p,{writes})=>{for(const w of writes){const key=w.update.name.slice(base.length+1),old=docs.get(key);if(w.currentDocument.updateTime)assert.equal(w.currentDocument.updateTime,old.updateTime);docs.set(key,{name:w.update.name,fields:{...old?.fields,...w.update.fields},updateTime:'v'+(++v)});}}};
 const pdf=Buffer.from('%PDF-1.4\nSynthetic attachment only\n%%EOF').toString('base64'),env={SITE_URL:'https://a.test'},req=(version=docs.get(path).updateTime,origin=env.SITE_URL)=>new Request(env.SITE_URL+'/api/admin/invoices/'+id+'/email',{method:'POST',headers:{Origin:origin},body:JSON.stringify({version,pdf})}),options={getToken:async()=> 'mock',send:async(url,init)=>{sends++;const mime=Buffer.from(JSON.parse(init.body).raw,'base64url').toString();assert.ok(mime.includes('Content-Disposition: attachment; filename="SW-001.pdf"'));assert.ok(mime.includes('To: test@example.invalid'));assert.ok(mime.includes(pdf));if(mode==='timeout')throw Error('timeout');return Response.json({id:'mock-receipt'});}};
 assert.equal((await invoiceMail(req('old'),env,db,id,options)).status,409);assert.equal((await invoiceMail(req(undefined,'https://evil.test'),env,db,id,options)).status,403);assert.equal((await invoiceMail(req(),env,db,id,options)).status,200);assert.equal(unpack(docs.get(path)).deliveryStatus,'sent');assert.equal(sends,1);assert.equal((await invoiceMail(req(),env,db,id,options)).status,409);assert.equal(sends,1);
 await db.patch(path,{deliveryStatus:'failed'});mode='timeout';assert.equal((await invoiceMail(req(),env,db,id,options)).status,503);assert.equal(unpack(docs.get(path)).deliveryStatus,'unknown');assert.equal((await invoiceMail(req(),env,db,id,options)).status,409);assert.equal(sends,2);
});
