import {base,fields,unpack,hash,database} from './firestore-rest.mjs';
import {sameOrigin} from './admin-auth.mjs';
const reply=(status,body)=>Response.json(body,{status,headers:{'Cache-Control':'no-store'}}),uuid=s=>/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(s);
export function validateTypes(types){if(!Array.isArray(types)||types.length>12)throw Error('types');const ids=new Set();return types.map(t=>{if(!/^[a-z0-9-]{2,40}$/.test(t.id)||ids.has(t.id)||typeof t.name!=='string'||!t.name.trim()||t.name.length>100||typeof t.nameEn!=='string'||t.nameEn.length>100||!Number.isInteger(t.duration)||t.duration<15||t.duration>180||!Number.isSafeInteger(t.priceBaisa)||t.priceBaisa<0||t.priceBaisa>10000000||typeof t.active!=='boolean'||(t.description!==undefined&&(typeof t.description!=='string'||t.description.length>600))||(t.descriptionEn!==undefined&&(typeof t.descriptionEn!=='string'||t.descriptionEn.length>600)))throw Error('type');ids.add(t.id);return {id:t.id,name:t.name.trim(),nameEn:t.nameEn.trim(),description:(t.description||'').trim(),descriptionEn:(t.descriptionEn||'').trim(),duration:t.duration,priceBaisa:t.priceBaisa,active:t.active};});}
async function settings(db){const doc=await db.read('portfolioSettings/consultations');return {doc,types:JSON.parse(unpack(doc)?.typesJson||'[]')};}
async function slots(db){let result=[],cursor;for(let p=0;p<20;p++){const rows=await db.api(base+':runQuery',{structuredQuery:{from:[{collectionId:'portfolioConsultationSlots'}],where:{fieldFilter:{field:{fieldPath:'start'},op:'GREATER_THAN_OR_EQUAL',value:{stringValue:new Date(Date.now()-86400000).toISOString()}}},orderBy:[{field:{fieldPath:'start'},direction:'ASCENDING'},{field:{fieldPath:'__name__'},direction:'ASCENDING'}],limit:100,...(cursor?{startAt:{values:[cursor.fields.start,{referenceValue:cursor.name}],before:false}}:{})}});const docs=rows.filter(r=>r.document).map(r=>r.document);result.push(...docs.map(d=>({...unpack(d),id:d.name.split('/').pop(),version:d.updateTime})));if(docs.length<100)return result;cursor=docs.at(-1);}throw Error('limit');}
async function body(request,limit=16000){const text=await request.text();if(new TextEncoder().encode(text).length>limit)throw Error('size');return JSON.parse(text);}
export async function consultationAdmin(request,env,db,route){
 const config=await settings(db);
 if(route==='consultations'&&request.method==='GET')return reply(200,{types:config.types,version:config.doc?.updateTime||'',slots:await slots(db)});
 if(!sameOrigin(request,env))return reply(403,{error:'origin'});
 const deletion=route.match(/^consultations\/slots\/([^/]+)$/);if(deletion&&uuid(deletion[1])&&request.method==='DELETE'){let input;try{input=await body(request);}catch{return reply(400,{error:'input'});}const path='portfolioConsultationSlots/'+deletion[1],guard=await db.read('portfolioSettings/calendarGuard'),doc=await db.read(path);if(!doc)return reply(404,{error:'missing'});if(input.version!==doc.updateTime||unpack(doc).bookingId)return reply(409,{error:'booked_or_stale'});await db.api(base+':commit',{writes:[{delete:base+'/'+path,currentDocument:{updateTime:doc.updateTime}},{update:{name:base+'/portfolioSettings/calendarGuard',fields:fields({updatedAt:new Date().toISOString()})},currentDocument:guard?{updateTime:guard.updateTime}:{exists:false}}]});return reply(200,{saved:true});}
 if(route==='consultations/types'&&request.method==='PUT'){let input,types;try{input=await body(request);types=validateTypes(input.types);}catch{return reply(400,{error:'types'});}if(input.version!==(config.doc?.updateTime||''))return reply(409,{error:'stale'});await db.api(base+':commit',{writes:[{update:{name:base+'/portfolioSettings/consultations',fields:fields({typesJson:JSON.stringify(types)})},currentDocument:config.doc?{updateTime:config.doc.updateTime}:{exists:false}}]});return reply(200,{saved:true});}
 if(route==='consultations/slots'&&request.method==='POST'){
  let input;try{input=await body(request);}catch{return reply(400,{error:'input'});}const type=config.types.find(t=>t.id===input.typeId&&t.active),start=Date.parse(input.start);if(!type||!Number.isFinite(start)||start<Date.now()+300000||start>Date.now()+180*86400000)return reply(400,{error:'slot'});
  const guard=await db.read('portfolioSettings/calendarGuard'),list=await slots(db),end=start+type.duration*60000;if(list.some(s=>start<Date.parse(s.end)&&end>Date.parse(s.start)))return reply(409,{error:'overlap'});
  const id=crypto.randomUUID();await db.api(base+':commit',{writes:[{verify:config.doc.name,currentDocument:{updateTime:config.doc.updateTime}},{update:{name:base+'/portfolioConsultationSlots/'+id,fields:fields({typeId:type.id,start:new Date(start).toISOString(),end:new Date(end).toISOString(),duration:type.duration,open:true,bookingId:''})},currentDocument:{exists:false}},{update:{name:base+'/portfolioSettings/calendarGuard',fields:fields({updatedAt:new Date().toISOString()})},currentDocument:guard?{updateTime:guard.updateTime}:{exists:false}}]});return reply(201,{id});
 }
 const match=route.match(/^consultations\/slots\/([^/]+)$/);if(match&&uuid(match[1])&&request.method==='PATCH'){let input;try{input=await body(request);}catch{return reply(400,{error:'input'});}const path='portfolioConsultationSlots/'+match[1],doc=await db.read(path);if(!doc)return reply(404,{error:'missing'});if(input.version!==doc.updateTime||unpack(doc).bookingId)return reply(409,{error:'booked_or_stale'});if(typeof input.open!=='boolean')return reply(400,{error:'input'});await db.patch(path,{open:input.open},doc.updateTime);return reply(200,{saved:true});}
 return reply(404,{error:'not_found'});
}
export async function consultationPublic(request,env,{db=database(env.FIREBASE_SERVICE_ACCOUNT_JSON),notify=()=>{}}={}){
 try{const config=await settings(db);
 if(request.method==='GET'){const available=(await slots(db)).filter(s=>s.open&&!s.bookingId&&Date.parse(s.start)>Date.now()+300000&&config.types.some(t=>t.id===s.typeId&&t.active&&t.duration===s.duration));return reply(200,{types:config.types.filter(t=>t.active),slots:available.map(s=>({id:s.id,typeId:s.typeId,start:s.start,end:s.end,duration:s.duration})),timeZone:'Asia/Muscat'});}
 if(request.method!=='POST')return reply(405,{error:'method'});if(!sameOrigin(request,env))return reply(403,{error:'origin'});
 let input;try{input=await body(request,10000);}catch{return reply(400,{error:'input'});}
 if(!uuid(input.requestId)||!uuid(input.slotId)||typeof input.name!=='string'||input.name.trim().length<2||input.name.length>100||typeof input.phone!=='string'||!/^\+?[0-9 ()-]{7,25}$/.test(input.phone)||input.phone.replace(/\D/g,'').length<7||typeof input.email!=='string'||input.email.length>254||! /^[A-Za-z0-9.!#$%&'*+/=?^_`{|}~-]+@[A-Za-z0-9](?:[A-Za-z0-9.-]*[A-Za-z0-9])?\.[A-Za-z]{2,}$/.test(input.email)||typeof input.message!=='string'||input.message.length>2000||input.consent!==true||input.website)return reply(400,{error:'input'});
 const digest=await hash(JSON.stringify({slotId:input.slotId,name:input.name.trim(),phone:input.phone,email:input.email,message:input.message})),path='portfolioInquiries/'+input.requestId;
 const existing=unpack(await db.read(path));if(existing)return existing.bookingHash===digest?reply(200,{reference:existing.reference,id:input.requestId}):reply(409,{error:'conflict'});
 const slotPath='portfolioConsultationSlots/'+input.slotId,doc=await db.read(slotPath),slot=unpack(doc),type=config.types.find(t=>t.id===slot?.typeId&&t.active);
 if(!slot||!type||!slot.open||slot.bookingId||Date.parse(slot.start)<=Date.now()+300000||type.duration!==slot.duration)return reply(409,{error:'unavailable'});
 if(input.priceBaisa!==type.priceBaisa||input.duration!==type.duration)return reply(409,{error:'price_changed'});
 const ip=request.headers.get('CF-Connecting-IP');if(!ip)return reply(503,{error:'config'});const ratePath='portfolioRateLimits/consult-'+await hash(ip),rate=await db.read(ratePath),r=unpack(rate)||{},now=Date.now(),count=r.windowStart>now-3600000?r.count:0;if(count>=5)return reply(429,{error:'rate_limit'});
 const counter=await db.read('portfolioSettings/requestCounter'),sequence=(unpack(counter)?.sequence||1000)+1,reference='SAL-'+sequence,language=input.language==='en'?'en':'ar',when=new Intl.DateTimeFormat(language,{timeZone:'Asia/Muscat',dateStyle:'full',timeStyle:'short'}).format(new Date(slot.start));
 const data={name:input.name.trim(),phone:input.phone,email:input.email,service:language==='en'?(type.nameEn||type.name):type.name,context:'consultation',kind:'contact',language,message:`${input.message}\n\n${when} (Asia/Muscat)\n${type.duration} min · ${(type.priceBaisa/1000).toFixed(3)} OMR`,consent:true,status:'new',reference,notes:'',bookingHash:digest,consultationSlot:input.slotId,consultationStart:slot.start,consultationPriceBaisa:type.priceBaisa,consultationDuration:type.duration,emailStatus:'pending',emailAttempts:0,ownerEmailStatus:'pending',ownerEmailAttempts:0};
 await db.api(base+':commit',{writes:[{update:{name:base+'/'+path,fields:fields(data)},currentDocument:{exists:false},updateTransforms:[{fieldPath:'createdAt',setToServerValue:'REQUEST_TIME'}]},{update:{name:base+'/'+slotPath,fields:fields({bookingId:input.requestId})},updateMask:{fieldPaths:['bookingId']},currentDocument:{updateTime:doc.updateTime}},{verify:config.doc.name,currentDocument:{updateTime:config.doc.updateTime}},{update:{name:base+'/portfolioSettings/requestCounter',fields:fields({sequence})},currentDocument:counter?{updateTime:counter.updateTime}:{exists:false}},{update:{name:base+'/'+ratePath,fields:fields({count:count+1,windowStart:count?r.windowStart:now})},currentDocument:rate?{updateTime:rate.updateTime}:{exists:false}}]});
 try{notify(input.requestId);}catch{}return reply(201,{id:input.requestId,reference});
 }catch(e){return reply(['FAILED_PRECONDITION','ALREADY_EXISTS','ABORTED'].includes(e.code)?409:503,{error:'retry'});}
}
